#!/usr/bin/env bash
# Displays Imformation about subdomains

# shellcheck disable=SC2086

# Usage:
# (1) ./0-world_wide_web 3akare.tech
# (2) ./0-world_wide_web 3akare.tech web-02


if [ "$#" = 1 ]
then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${subdomains[@]}"
    do
        record_type=$(dig "$sub_domain.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
        ip_address=$(dig "$sub_domain.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
        echo "The subdomain $sub_domain is a $record_type record and points to $ip_address"
    done
elif [ "$#" = 2 ]
then
    record_type=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
    ip_address=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
    echo "The subdomain $2 is a $record_type record and points to $ip_address"
fi
#!/usr/bin/env bash
# script to report information about server domains
# shellcheck disable=SC2086
check_domain() {
	# awk will use record seperator of space
	# space sperated list of sub domains
	SUBDOMAINS='www lb-01 web-01 web-02'

	if [ -z "$1" ]; then
		exit
	fi
	# no sub domain specified, do all
	if [ -z "$2" ]; then
		echo "$SUBDOMAINS" | awk -v domain="$1"\
		'BEGIN { RS=" " }
		{split($0,ARR," ");
		cmd = "dig " ARR[1]"."domain " | grep -A1 \"ANSWER SECTION:\" | tail -n1";
		system(cmd)
		close(cmd)}' | awk\
		'{
		split($0, DOMS, ".");
		print "The subdomain " DOMS[1] " is a " $4 " record and points to " $5}'
	else
		dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tail -n1 | awk\
		'{
		split($0, DOMS, ".");
		print "The subdomain " DOMS[1] " is a " $4 " record and points to " $5}'
	fi
}
check_domain "$1" "$2"
